name: CI - FuegoGT Wallet

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            fuego-tauri/src-tauri/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # macOS dependencies are handled by Tauri automatically
          echo "macOS dependencies handled by Tauri"

      - name: Install frontend dependencies
        working-directory: fuego-tauri
        run: npm ci

      - name: Run frontend linting
        working-directory: fuego-tauri
        run: |
          npm run lint --if-present || echo "No lint script found"
          npm run type-check --if-present || echo "No type-check script found"

      - name: Run frontend tests
        working-directory: fuego-tauri
        run: npm test -- --passWithNoTests

      - name: Run Rust tests
        working-directory: fuego-tauri/src-tauri
        run: cargo test --verbose

      - name: Run Rust clippy
        working-directory: fuego-tauri/src-tauri
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Run Rust fmt check
        working-directory: fuego-tauri/src-tauri
        run: cargo fmt --all -- --check

      - name: Build application (development)
        working-directory: fuego-tauri
        run: npm run tauri build -- --debug
        continue-on-error: true

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        working-directory: fuego-tauri
        run: npm ci

      - name: Run npm audit
        working-directory: fuego-tauri
        run: npm audit --audit-level=moderate

      - name: Run Rust audit
        working-directory: fuego-tauri/src-tauri
        run: |
          cargo install cargo-audit
          cargo audit

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        working-directory: fuego-tauri
        run: npm ci

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, typescript, rust

      - name: Check code formatting
        working-directory: fuego-tauri/src-tauri
        run: cargo fmt --all -- --check

      - name: Check code style
        working-directory: fuego-tauri/src-tauri
        run: cargo clippy --all-targets --all-features -- -D warnings

  build-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          # macOS dependencies are handled by Tauri automatically
          echo "macOS dependencies handled by Tauri"

      - name: Install frontend dependencies
        working-directory: fuego-tauri
        run: npm ci

      - name: Check if application builds
        working-directory: fuego-tauri
        run: npm run tauri build -- --debug
        continue-on-error: true
